name: Publish Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run compile

      - name: Package extension
        run: npx vsce package

      - name: Determine package name
        id: package
        run: echo "vsix=$(ls *.vsix)" >> $GITHUB_OUTPUT

      - name: Publish to VS Code Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx vsce publish --packagePath "${{ steps.package.outputs.vsix }}" --pat "$VSCE_PAT"

      - name: Publish to Open VSX
        env:
          OVSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}
        run: npx ovsx publish "${{ steps.package.outputs.vsix }}" --pat "$OVSX_TOKEN"
